import Head from "next/head"
import { Navabar } from "../Navabar";
import styles  from './Main.module.css';
import { FC } from 'react';

interface MainProps {
  children: React.ReactNode;
}

export const MainLayout : React.FC<MainProps>= ({ children }) => {
  return (
    <div className={styles.container}>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <Navabar/>
    <main className={styles.main}>
   {children}
    

    </main>
  </div>
  )
}
